[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
source ~/.config/nvim/config/neoterm.rc.vim
'''

#[[plugins]]
#repo = "ncm2/float-preview"


#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#rev = 'next'
#build = 'bash install.sh'
#hook_add = '''
#source ~/.config/nvim/config/lsp-neovim.rc.vim
#'''

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#hook_add = '''
#source ~/.config/nvim/config/deoplete.rc.vim
#'''

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/config/cocconfig.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/config/lightline.rc.vim
'''
[[plugins]]
repo = "junegunn/fzf.vim"
hook_add = '''
source ~/.config/nvim/config/fzf.rc.vim
'''
