[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = "rust-lang/rust.vim"
on_ft = "rust"

#[[plugins]]
#repo = "racer-rust/vim-racer"
#on_ft = "rust"
#hook_source = '''
#    let g:racer_cmd = "/home/ryoj/.local/bin/racer"
#    let g;racer_experimental_completer = 1
#'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'numirias/semshi'
on_ft = 'python'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'
